pyuic5 -x Doctor3.ui -o Doctor3.py

cloud

https://github.com/conda-forge/pyqt-feedstock

https://stackoverflow.com/questions/41420173/segmentation-fault-core-dumped-error-in-pyqt5

https://stackoverflow.com/questions/57427668/how-to-install-pyqt5-on-a-virtual-machine
libgl1-mesa-dev
libxss-dev
libasound2-dev

https://medium.com/google-cloud/linux-gui-on-the-google-cloud-platform-800719ab27c5


sftp://naya@34.67.193.78:122/home/naya/miniconda3/bin/python)

/home/naya/miniconda3/bin/python

/tmp/pycharm_project_471

sudo docker exec -it cnt7-naya-cdh63 bash

conda install  pyqt5-sip pyqtchart pyqtwebengine

 conda install -c conda-forge pyqt5-sip pyqtchart pyqtwebengine
 
 conda install -c conda-forge pyqtwebengine
 
  conda install -c conda-forge pyqt5-sip
  
  # cat /etc/ssh/sshd_config |grep X11Forw
#X11Forwarding no
X11Forwarding yes
  vi /etc/ssh/sshd_config
  ForwardX11 yes
  
  https://forum.qt.io/topic/117922/qt5-with-opengl-on-raspberry-pi-0-getting-error-qxcbconnection-could-not-connect-to-display-could-not-connect-to-any-x-display
 
 his can take several minutes.  Press CTRL-C to abort.
failed                                                                                                          

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package dbus conflicts for:
pyqtwebengine -> dbus[version='>=1.13.6,<2.0a0']
pyqtwebengine -> qt-webengine[version='>=5.15.4,<5.16.0a0'] -> dbus[version='>=1.13.18,<2.0a0']

Package qt-main conflicts for:
pyqtwebengine -> qt-webengine[version='>=5.15.4,<5.16.0a0'] -> qt-main[version='>=5.15,<6.0a0']
pyqtwebengine -> qt-main[version='5.15.*|>=5.15.3,<5.16.0a0|>=5.15.4,<5.16.0a0|>=5.15.2,<5.16.0a0']

Package pyqt5-sip conflicts for:
pyqt5-sip
pyqtchart -> pyqt[version='>=5.15.7,<5.16.0a0'] -> pyqt5-sip[version='12.11.0|12.9.0|12.9.0|12.9.0|12.9.0|12.9.0|12.9.0|12.9.0|12.9.0|4.19.18|4.19.18|4.19.18|4.19.18|4.19.18|4.19.18|4.19.18|4.19.18|4.19.18|4.19.18|4.19.18|4.19.18|4.19.18|4.19.18|4.19.18|4.19.18',build='py39he80948d_5|py36hc4f0c31_5|py37hcd2ae1e_6|py38h709712a_6|py36hc4f0c31_7|py39he80948d_7|py39he80948d_8|py37hd23a5d3_1|py38hfa26641_1|py39h5a03fae_1|py310hd8f1fbe_1|py39h6a678d5_0|py310h6a678d5_1|py38h6a678d5_1|py37h6a678d5_1|py39h6a678d5_1|py39h5a03fae_0|py37hd23a5d3_0|py310hd8f1fbe_0|py38hfa26641_0|py37h6a678d5_0|py310h6a678d5_0|py38h6a678d5_0|py310hd8f1fbe_0|py37hd23a5d3_0|py39h5a03fae_0|py38hfa26641_0|py37hcd2ae1e_8|py38h709712a_8|py310h122e73d_8|py37hcd2ae1e_7|py38h709712a_7|py39he80948d_6|py36hc4f0c31_6|py38h709712a_5|py37hcd2ae1e_5']
pyqtwebengine -> pyqt[version='>=5.15.7,<5.16.0a0'] -> pyqt5-sip[version='12.11.0|12.9.0|12.9.0|12.9.0|12.9.0|12.9.0|12.9.0|12.9.0|12.9.0|4.19.18|4.19.18|4.19.18|4.19.18|4.19.18|4.19.18|4.19.18|4.19.18|4.19.18|4.19.18|4.19.18|4.19.18|4.19.18|4.19.18|4.19.18|4.19.18',build='py39he80948d_5|py36hc4f0c31_5|py37hcd2ae1e_6|py38h709712a_6|py36hc4f0c31_7|py39he80948d_7|py39he80948d_8|py37hd23a5d3_1|py38hfa26641_1|py39h5a03fae_1|py310hd8f1fbe_1|py39h6a678d5_0|py310h6a678d5_1|py38h6a678d5_1|py37h6a678d5_1|py39h6a678d5_1|py39h5a03fae_0|py37hd23a5d3_0|py310hd8f1fbe_0|py38hfa26641_0|py37h6a678d5_0|py310h6a678d5_0|py38h6a678d5_0|py310hd8f1fbe_0|py37hd23a5d3_0|py39h5a03fae_0|py38hfa26641_0|py37hcd2ae1e_8|py38h709712a_8|py310h122e73d_8|py37hcd2ae1e_7|py38h709712a_7|py39he80948d_6|py36hc4f0c31_6|py38h709712a_5|py37hcd2ae1e_5']

Package expat conflicts for:
pyqtchart -> qt-main[version='>=5.15.4,<5.16.0a0'] -> expat[version='>=2.2.10,<3.0.0a0|>=2.2.10,<3.0a0|>=2.4.1,<3.0a0|>=2.4.4,<3.0a0|>=2.4.6,<3.0a0|>=2.4.8,<3.0a0|>=2.4.2,<3.0a0|>=2.3.0,<3.0.0a0|>=2.2.9,<3.0.0a0|>=2.2.5,<3.0.0a0|>=2.2.6,<3.0a0|>=2.4.7,<3.0a0']
pyqtwebengine -> qt-main[version='>=5.15.4,<5.16.0a0'] -> expat[version='>=2.2.10,<3.0.0a0|>=2.2.10,<3.0a0|>=2.4.6,<3.0a0|>=2.4.8,<3.0a0|>=2.4.4,<3.0a0|>=2.4.1,<3.0a0|>=2.4.2,<3.0a0|>=2.3.0,<3.0.0a0|>=2.2.9,<3.0.0a0|>=2.2.5,<3.0.0a0|>=2.2.6,<3.0a0|>=2.4.7,<3.0a0']The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.17=0
  - pyqt5-sip -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - pyqtchart -> qt-main[version='>=5.15.4,<5.16.0a0'] -> __glibc[version='>=2.17|>=2.17,<3.0.a0']
  - pyqtwebengine -> qt-main[version='>=5.15.4,<5.16.0a0'] -> __glibc[version='>=2.17|>=2.17,<3.0.a0']
  - python=3.6.6 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.17


find / -name "qt5pi" 
find -type f -name "qt5*"


find -type f -name "qt5*"
./.conda/pkgs/libboost-1.73.0-h3ff78a5_11/share/boost-build/src/tools/qt5.jam
./miniconda3/pkgs/libboost-1.67.0-h46d08c1_4/share/boost-build/src/tools/qt5.jam
./miniconda3/pkgs/pyqt5-sip-4.19.18-py36hc4f0c31_7/info/recipe/parent/qt5_dll.diff
./miniconda3/share/boost-build/src/tools/qt5.jam